config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"

  get "/contact", to: "articles#contact"
  get "/create", to: "articles#create"
  get "/finder", to: "articles#finder"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   validate: true
  attribute :nickname,  captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "gabejonuk@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def contact
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:success] = 'Message sent!'
    else
      flash.now[:error] = 'Could not send message'
      render :new
    end
  end

  def finder
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_contactContent.html.haml
.row
  = image_tag "hubcitysealtitle.svg", style: 'width:80%; margin-left:auto; margin-right:auto;'
.row.pt-3
  .col-1
  .col-3.col-xs-6.tab.mx-1
    = link_to "Home",  root_path, :class => "tab-link" 
  .col-3.col-xs-6.tab.mx-1.active
    = link_to "Contact",  contact_path, :class => "tab-link-active" 
  .col-3.col-xs-6.tab.mx-1
    = link_to "Read",  finder_path, :class => "tab-link" 

.row.photocopy-mask.pt-4
  .col-1
  .col{id: "shadowbox"}
    .h1.arial.main-text.rainbow_text_animated NOW SEEKING TRIPPERS
    .h2.arial.main-text.fst-italic Capture your experience of the Deadening Escape, joyful creation of alternative Culture, beyond the Eye-Gulp Of The Screen
    .h2.arial.main-text <br> The tantalysis of pulp & paper wage labour of the copy shop <u>NOW TO BE HELD IN YOUR HAND</u>. Observe the culture & BECOME THE CULTURE -spaces btwn each molecule dimnsh ass hand passes the paper, briefly,, Connect
    = image_tag "hubcityemail.png", style: 'width:80%; margin-left:auto; margin-right:auto;'
    .h2.arial.main-text.pt-4 Drawings by MAMH & ESC <br> Layout /graphic design by KMVP <br> Website by Roy (gabejonuk@gmail.com)

app/views/articles/_finderContent.html.haml
.row
  = image_tag "hubcitysealtitle.svg", style: 'width:80%; margin-left:auto; margin-right:auto;'
.row.pt-3
  .col-1
  .col-3.col-xs-6.tab.mx-1
    = link_to "Home",  root_path, :class => "tab-link" 
  .col-3.col-xs-6.tab.mx-1
    = link_to "Contact",  contact_path, :class => "tab-link" 
  .col-3.col-xs-6.tab.mx-1.active
    = link_to "Read",  finder_path, :class => "tab-link-active" 

.row.photocopy-mask.pt-4
  .col-1
  .col{id: "shadowbox"}
    .h1.arial.main-text.rainbow_text_animated RECIEVE WORD, ICONOCLAST OF THOSE THAT CAME BEFORE
    .h2.arial.main-text.fst-italic Find a Copy:

app/views/articles/_indexContent.html.haml
.row
  = image_tag "hubcitysealtitle.svg", style: 'width:80%; margin-left:auto; margin-right:auto;'
.row.pt-3
  .col-1
  .col-3.col-xs-4.tab.mx-1.active
    = link_to "Home",  root_path, :class => "tab-link-active" 
  .col-3.col-xs-4.tab.mx-1
    = link_to "Contact",  contact_path, :class => "tab-link" 
  .col-3.col-xs-4.tab.mx-1
    = link_to "Read",  finder_path, :class => "tab-link"  
-# .row.photocopy-mask.pt-4
-#   .col-1
-#   .col
-#     .h2 Texttextloremipsum Texttextloremipsum Texttextloremipsum Texttextloremipsum
-#     .p Texttextloremipsum Texttextloremipsum Texttextloremipsum Texttextloremipsum
.row.photocopy-mask.pt-2
  .col-1.d-none.d-md-block
  .col
    = image_tag "howto.jpg", style: 'width:100%; height:80%; margin-left:auto; margin-right:auto;'
    .h1.arial.main-text.rainbow_text_animated.pt-2 To read and to write is to hug with the mind,

app/views/articles/contact.html.haml
.container
  .col-1.d-none.d-md-block
  .col-10.main.tilt-left.zine.d-none.d-md-block
    = render "articles/contactContent"
  .col-1.d-none.d-md-block
  .d-block.d-md-none.mobile
    = render "articles/contactContent"

app/views/articles/finder.html.haml
.container
  .col-1.d-none.d-md-block
  .col-10.main.tilt-left.zine.d-none.d-md-block
    = render "articles/finderContent"
  .col-1.d-none.d-md-block
  .d-block.d-md-none.mobile
    = render "articles/finderContent"

app/views/articles/index.html.haml
.container
  .col-1.d-none.d-md-block
  .col-10.main.tilt-left.zine.d-none.d-md-block
    = render "articles/indexContent"
  .col-1.d-none.d-md-block
  .d-block.d-md-none.mobile
    = render "articles/indexContent"

app/views/layouts/application.html.haml
!!! html
!!!
%html
  %head
    %title The Hub City Seal
    %meta{:name => "viewport", :content => "width=device-width initial-scale=1"}
    %meta{:charset => "utf-8" }
    %meta{:author => "CorduroyDev"}
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = stylesheet_link_tag "styles", "data-turbo-track": "reload"

    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true

  %body
    = yield